FROM redhat/ubi8:8.10
ARG OPENSHIFT_INSTALL_VERSION=4.15.18

# Install packages
RUN yum install -y git \
    && yum clean all \
    && rm -rf /var/cache/yum

# Install the OpenShift installer binary
RUN curl -o /tmp/openshift-install.tar.gz \
    https://mirror.openshift.com/pub/openshift-v4/clients/ocp/latest/openshift-install-linux-$OPENSHIFT_INSTALL_VERSION.tar.gz \
    && tar -xzf /tmp/openshift-install.tar.gz -C /usr/local/bin openshift-install \
    && rm /tmp/openshift-install.tar.gz