heat_template_version: 2018-08-31

description: OpenStack Heat template to deploy a single-node microk8s.

parameters:
  image_id:
    type: string
    label: Image ID
    description: Image to be used for compute instance. Ubuntu is recommended.
  instance_type:
    type: string
    label: Instance Type
    description: Type of instance (flavor) to be used
  network:
    type: string
    label: Network
    description: Network for the instance

resources:
  inbound_ssh_security_group:
    type: OS::Neutron::SecurityGroup
    properties:
      name: inbound_ssh_security_group
      description: Security Group for allowing SSH access
      rules:
        - protocol: tcp
          port_range_min: 22
          port_range_max: 22
          remote_ip_prefix: 0.0.0.0/0  # Allows ingress from any IP address
  inbound_http_security_group:
    type: OS::Neutron::SecurityGroup
    properties:
      name: inbound_http_security_group
      description: Security Group for allowing HTTP access
      rules:
        - protocol: tcp
          port_range_min: 80
          port_range_max: 80
          remote_ip_prefix: 0.0.0.0/0  # Allows ingress from any IP address
  inbound_https_security_group:
    type: OS::Neutron::SecurityGroup
    properties:
      name: inbound_https_security_group
      description: Security Group for allowing HTTPS access
      rules:
        - protocol: tcp
          port_range_min: 443
          port_range_max: 443
          remote_ip_prefix: 0.0.0.0/0  # Allows ingress from any IP address
  microk8s_single:
    type: OS::Nova::Server
    properties:
      key_name: microk8s
      image: { get_param: image_id }
      flavor: { get_param: instance_type }
      networks:
        - network: { get_param: network }
      security_groups:
        - default
        - get_resource: inbound_ssh_security_group
        - get_resource: inbound_http_security_group
        - get_resource: inbound_https_security_group
      user_data: |
        #!/bin/sh
        snap install microk8s --classic --channel=latest/stable
        usermod -a -G microk8s ubuntu
        su - ubuntu
        mkdir -p /home/ubuntu/.kube
        chmod 0700 /home/ubuntu/.kube
        echo "alias kubectl='microk8s kubectl'" >> /home/ubuntu/.bash_aliases
        microk8s enable dashboard ingress
